apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fullnameOverride }}-config
  namespace: {{ .Values.namespace.name }}
data:
{{- range $key, $value := .Values.env.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

