apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride }}-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}

