apiVersion: v1
kind: ConfigMap
metadata:
  name: pronunt-worker-service-config
  namespace: prism
data:
  APP_NAME: pronunt-worker-service
  APP_ENV: production
  APP_HOST: 0.0.0.0
  APP_PORT: "8000"
  LOG_LEVEL: INFO
  RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  AGGREGATOR_SERVICE_URL: http://pronunt-aggregator-service:8000

